In [ ]:
# ============================================================
# LIONS CAMP SCRAPER — Google Colab
# Scrape → filtre 2026 → extrait PDF à la volée → JSON
# Site italien → pays extraits de l'URL, traduits EN
# Régions détaillées : North / Middle / South America
# USA : country + state depuis l'URL
# ============================================================

# ── 1. Installation ──────────────────────────────────────────
!pip install requests beautifulsoup4 pdfplumber -q

# ── 2. Imports ───────────────────────────────────────────────
import requests, json, re, os, io
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from IPython.display import display
import pdfplumber
import pandas as pd

# ── 3. Config ────────────────────────────────────────────────
BASE_URL    = "https://www.scambigiovanili-lions.org/campi-lions-esteri-nel-mondo"
BASE_DOMAIN = "https://www.scambigiovanili-lions.org"
URL_PREFIX_SEGMENTS = {"images", "doc-campi-esteri", "doc-campi-italia"}

OUTPUT_JSON = "lions_camps_2026.json"
PDF_FOLDER  = "/content/pdf_camps"
TARGET_YEAR = "2026"

os.makedirs(PDF_FOLDER, exist_ok=True)

# ── 4. Dictionnaire Italien → Anglais ────────────────────────
ITALIAN_TO_ENGLISH = {
    # Europa
    "austria"               : "Austria",
    "belgio"                : "Belgium",
    "danimarca"             : "Denmark",
    "finlandia"             : "Finland",
    "francia"               : "France",
    "germania"              : "Germany",
    "gran bretagna"         : "United Kingdom",
    "regno unito"           : "United Kingdom",
    "uk"                    : "United Kingdom",
    "grecia"                : "Greece",
    "irlanda"               : "Ireland",
    "islanda"               : "Iceland",
    "italia"                : "Italy",
    "campi italia"          : "Italy",
    "lussemburgo"           : "Luxembourg",
    "malta"                 : "Malta",
    "norvegia"              : "Norway",
    "olanda"                : "Netherlands",
    "paesi bassi"           : "Netherlands",
    "polonia"               : "Poland",
    "portogallo"            : "Portugal",
    "repubblica ceca"       : "Czech Republic",
    "romania"               : "Romania",
    "slovacchia"            : "Slovakia",
    "slovenia"              : "Slovenia",
    "spagna"                : "Spain",
    "svezia"                : "Sweden",
    "svizzera"              : "Switzerland",
    "turchia"               : "Turkey",
    "ucraina"               : "Ukraine",
    "ungheria"              : "Hungary",
    "croazia"               : "Croatia",
    "serbia"                : "Serbia",
    "bulgaria"              : "Bulgaria",
    "estonia"               : "Estonia",
    "lettonia"              : "Latvia",
    "lituania"              : "Lithuania",
    # Nord America
    "canada"                : "Canada",
    "stati-uniti"           : "United States",
    "stati uniti"           : "United States",
    "usa"                   : "United States",
    # America Centrale
    "costa-rica"            : "Costa Rica",
    "costa rica"            : "Costa Rica",
    "cuba"                  : "Cuba",
    "guatemala"             : "Guatemala",
    "honduras"              : "Honduras",
    "messico"               : "Mexico",
    "panama"                : "Panama",
    "repubblica-dominicana" : "Dominican Republic",
    "repubblica dominicana" : "Dominican Republic",
    # Sud America
    "argentina"             : "Argentina",
    "bolivia"               : "Bolivia",
    "brasile"               : "Brazil",
    "cile"                  : "Chile",
    "colombia"              : "Colombia",
    "ecuador"               : "Ecuador",
    "paraguay"              : "Paraguay",
    "perù"                  : "Peru",
    "peru"                  : "Peru",
    "uruguay"               : "Uruguay",
    "venezuela"             : "Venezuela",
    # Asia-Pacifico
    "australia"             : "Australia",
    "cina"                  : "China",
    "mongolia"              : "Mongolia",
    "giappone"              : "Japan",
    "india"                 : "India",
    "indonesia"             : "Indonesia",
    "nuova-zelanda"         : "New Zealand",
    "nuova zelanda"         : "New Zealand",
    "corea-del-sud"         : "South Korea",
    "corea del sud"         : "South Korea",
    "taiwan"                : "Taiwan",
    "thailandia"            : "Thailand",
    "filippine"             : "Philippines",
    "vietnam"               : "Vietnam",
    # Africa
    "egitto"                : "Egypt",
    "etiopia"               : "Ethiopia",
    "ghana"                 : "Ghana",
    "kenya"                 : "Kenya",
    "marocco"               : "Morocco",
    "nigeria"               : "Nigeria",
    "sudafrica"             : "South Africa",
    "sud-africa"            : "South Africa",
    "tanzania"              : "Tanzania",
    "tunisia"               : "Tunisia",
    # Medio Oriente
    "emirati-arabi"         : "UAE",
    "emirati arabi"         : "UAE",
    "giordania"             : "Jordan",
    "israele"               : "Israel",
    "libano"                : "Lebanon",
}

# ── 5. Pays → Région ─────────────────────────────────────────
COUNTRY_REGION = {
    # Europe
    "Austria":"Europe","Belgium":"Europe","Denmark":"Europe",
    "Finland":"Europe","France":"Europe","Germany":"Europe",
    "United Kingdom":"Europe","Greece":"Europe","Ireland":"Europe",
    "Iceland":"Europe","Italy":"Europe","Luxembourg":"Europe","Malta":"Europe",
    "Norway":"Europe","Netherlands":"Europe","Poland":"Europe",
    "Portugal":"Europe","Czech Republic":"Europe","Romania":"Europe",
    "Slovakia":"Europe","Slovenia":"Europe","Spain":"Europe",
    "Sweden":"Europe","Switzerland":"Europe","Turkey":"Europe",
    "Ukraine":"Europe","Hungary":"Europe","Croatia":"Europe",
    "Serbia":"Europe","Bulgaria":"Europe","Estonia":"Europe",
    "Latvia":"Europe","Lithuania":"Europe",
    # North America
    "Canada":"North America",
    "United States":"North America",
    # Middle America
    "Costa Rica":"Middle America","Cuba":"Middle America",
    "Guatemala":"Middle America","Honduras":"Middle America",
    "Mexico":"Middle America","Panama":"Middle America",
    "Dominican Republic":"Middle America",
    # South America
    "Argentina":"South America","Bolivia":"South America",
    "Brazil":"South America","Chile":"South America",
    "Colombia":"South America","Ecuador":"South America",
    "Paraguay":"South America","Peru":"South America",
    "Uruguay":"South America","Venezuela":"South America",
    # Asia-Pacific
    "Australia":"Asia-Pacific","China":"Asia-Pacific","Nepal":"Asia-Pacific",
    "Japan":"Asia-Pacific","India":"Asia-Pacific","Sri Lanka":"Asia-Pacific",
    "Indonesia":"Asia-Pacific","New Zealand":"Asia-Pacific","Mongolia":"Asia-Pacific",
    "South Korea":"Asia-Pacific","Taiwan":"Asia-Pacific",
    "Thailand":"Asia-Pacific","Philippines":"Asia-Pacific",
    "Vietnam":"Asia-Pacific",
    # Africa
    "Egypt":"Africa","Ethiopia":"Africa","Ghana":"Africa",
    "Kenya":"Africa","Morocco":"Africa","Namibia":"Africa", "Nigeria":"Africa",
    "South Africa":"Africa","Tanzania":"Africa","Tunisia":"Africa",
    # Middle East
    "UAE":"Middle East","Jordan":"Middle East",
    "Israel":"Middle East","Lebanon":"Middle East",
}

# ── 6. Traduction nom de pays ─────────────────────────────────
def translate_country(raw_slug):
    """
    raw_slug : segment d'URL brut, ex. 'stati-uniti', 'gran-bretagna'
    Essaie d'abord le slug exact, puis le slug avec espaces,
    puis matching partiel, sinon retourne le slug capitalisé.
    """
    slug_dash  = raw_slug.lower().strip()          # 'stati-uniti'
    slug_space = slug_dash.replace("-", " ")       # 'stati uniti'

    for key in (slug_dash, slug_space):
        if key in ITALIAN_TO_ENGLISH:
            return ITALIAN_TO_ENGLISH[key]

    # Matching partiel
    for ita, eng in ITALIAN_TO_ENGLISH.items():
        if ita in slug_space:
            return eng

    return slug_dash.replace("-", " ").title()     # fallback

# ── 7. Extraction pays + région + state + année depuis l'URL ──
#
#  Structure réelle :
#    /images/doc-campi-esteri/country/year/camp.pdf
#    /images/doc-campi-esteri/stati-uniti/state/year/camp.pdf
#
URL_PREFIX_SEGMENTS = {"images", "doc-campi-esteri", "doc-campi-italia"}

def fix_year(raw_year):
    """Corrige les typos d'année fréquentes ex: 2926 → 2026."""
    if not raw_year or not raw_year.isdigit():
        return None
    YEAR_FIXES = {
        "2926": "2026",
        "2016": "2026",  # typo possible
        "2062": "2026",  # inversion chiffres
        "2206": "2026",  # inversion chiffres
    }
    if raw_year in YEAR_FIXES:
        print(f"    ⚠️  Typo année corrigée : {raw_year} → {YEAR_FIXES[raw_year]}")
        return YEAR_FIXES[raw_year]
    return raw_year

def parse_link_text(link_text, pdf_name):
    """Extrait année et camp_name depuis le texte du lien HTML.

    Formats attendus :
      "2026 - Lionscamp Sound of Music"
      "2026 Lionscamp Sound of Music"
      "Lionscamp Sound of Music"   ← fallback sans année
    """
    text = link_text.strip()

    # Cherche une année 202x en début de chaîne
    match = re.match(r"^(202\d)\s*[-–:]?\s*(.+)$", text)
    if match:
        year_from_link = fix_year(match.group(1))
        camp_name      = match.group(2).strip()
    else:
        year_from_link = None
        camp_name      = text if text else pdf_name.replace(".pdf", "")

    return camp_name, year_from_link

def guess_country_region(pdf_url):
    parsed = urlparse(pdf_url)

    # Segments non vides, on retire le préfixe connu
    parts = [
        p for p in parsed.path.split("/")
        if p.strip() and p.lower() not in URL_PREFIX_SEGMENTS
    ]
    # Standard : parts = [country, year, camp.pdf]
    # USA      : parts = [country, state, year, camp.pdf]

    raw_country = parts[0] if len(parts) > 0 else ""
    country     = translate_country(raw_country)
    region      = COUNTRY_REGION.get(country, "Other")
    state       = None
    year        = None

    if country == "United States" or country == "Canada" and len(parts) >= 4:
        # USA, Canada : country / state / year / camp.pdf
        raw_state = parts[1].replace("-", " ").replace("_", " ")
        state     = raw_state.strip().title()
        year      = parts[2] if parts[2].isdigit() else None
        year      = fix_year(year)
    elif country == "Italy":
        year      = none
    elif len(parts) >= 2:
        # Standard : country / year / camp.pdf
        year      = parts[1] if parts[1].isdigit() else None
        year      = fix_year(year)

    return country, region, state, year

# ── 8. Extraction texte PDF depuis bytes ─────────────────────
def extract_text_from_bytes(pdf_bytes):
    raw_text = ""
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            t = page.extract_text()
            if t:
                raw_text += t + "\n"
    return raw_text

# ── 9. Détection année dans le texte ─────────────────────────
def extract_year_from_pdf(raw_text):
    years = re.findall(r"\b(202[0-9])\b", raw_text)
    return years[0] if years else None

# ── 10. Parsing champs Lions Camp ─────────────────────────────
FIELD_MAP = {
    "Camp Location"        : "camp_location",
    "From/to"              : "dates",
    "Age"                  : "age_range",
    "Camp fee"             : "camp_fee",
    "Activities"           : "activities",
    "Family Stay"          : "family_stay",
    "Official Language"    : "official_language",
    "Camp Contact"         : "camp_contact",
    "Email"                : "email",
    "Phone"                : "phone",
    "Application Dead line": "application_deadline",
    "Website"              : "website",
}

def parse_camp_fields(raw_text,camp_name):
    lines = [l.strip() for l in raw_text.splitlines() if l.strip()]

    data = {"camp_name": camp_name}

    i = 0
    while i < len(lines):
        line    = lines[i]
        matched = False
        for label, key in FIELD_MAP.items():
            if line.startswith(label):
                value_inline = line[len(label):].strip()
                if value_inline:
                    if key == "activities":
                        full_value = value_inline
                        j = i + 1
                        while j < len(lines) and not any(
                            lines[j].startswith(lbl) for lbl in FIELD_MAP
                        ):
                            full_value += " " + lines[j]
                            j += 1
                        data[key] = full_value.strip()
                        i = j
                    else:
                        data[key] = value_inline
                        i += 1
                elif i + 1 < len(lines):
                    data[key] = lines[i + 1]
                    i += 2
                else:
                    data[key] = ""
                    i += 1
                matched = True
                break
        if not matched:
            i += 1

    # Enrichissement dates
    if "dates" in data:
        parts = re.split(r"\s*[\.\-]\s*", data["dates"])
        if len(parts) == 2:
            data["date_start"] = parts[0].strip()
            data["date_end"]   = parts[1].strip()

    # Enrichissement âge
    if "age_range" in data:
        ages = re.split(r"[/\-]", data["age_range"])
        if len(ages) == 2:
            try:
                data["age_min"] = int(ages[0].strip())
                data["age_max"] = int(ages[1].strip())
            except ValueError:
                pass

    # Enrichissement fee
    if "camp_fee" in data:
        fee_num = re.sub(r"[^\d\.]", "", data["camp_fee"])
        data["camp_fee_eur"] = float(fee_num) if fee_num else None

    return data

In [ ]:
# ── 11. Scraping des liens PDF ────────────────────────────────
print("🌐 Scraping de la page principale...")
resp = requests.get(BASE_URL, timeout=15)
soup = BeautifulSoup(resp.text, "html.parser")

pdf_links = [
    (a.text.strip(), urljoin(BASE_DOMAIN, a["href"]))
    for a in soup.find_all("a", href=True)
    if ".pdf" in a["href"].lower()
]

print(f"🔗 {len(pdf_links)} liens PDF trouvés\n")

# ── 12. Traitement PDF à la volée ─────────────────────────────
results  = []
skipped  = []
errors   = []
log_rows = []

for idx, (link_text, pdf_url) in enumerate(pdf_links, 1):

    pdf_name = pdf_url.split("/")[-1]
    print(f"[{idx:>3}/{len(pdf_links)}] ⚙️  {pdf_name}", end="...")

    try:

        # ── Nom du camp + année depuis le lien HTML ───────────
        camp_name, year_from_link = parse_link_text(link_text, pdf_name)

        # ── Pays + région + state + année depuis l'URL ────────
        country, region, state, year_from_url = guess_country_region(pdf_url)

        # ── Année finale : URL prioritaire, lien en fallback ──
        year = year_from_link or year_from_url

        #if country != "Italy":
        # Filtre AVANT download pour tous les autres années
        if year != TARGET_YEAR:
             print(f"⏭️ {camp_name} / {country} / {year} ignoré ")
             skipped.append({"file": pdf_name, "camp_name": camp_name, "year": year})
             log_rows.append([camp_name, year or "?", "⏭️ ignoré", "", ""])
             continue

        # Téléchargement en mémoire
        r = requests.get(pdf_url, timeout=15)
        r.raise_for_status()
        pdf_bytes = r.content

        raw_text = extract_text_from_bytes(pdf_bytes)

        # ── Pour l'Italie : détection année depuis le texte ───
        #if country == "Italy":
        #    year = extract_year_from_pdf(raw_text)

        # Parsing champs
        camp_data = parse_camp_fields(raw_text, camp_name)

        record = {
            "source_url" : pdf_url,
            "pdf_file"   : pdf_name,
            "year"       : year,
            "region"     : region,
            "country"    : country,
            **({"state": state} if state else {}),
            **camp_data
        }
        results.append(record)

        # Sauvegarde PDF sur disque uniquement si 2026
        pdf_path = os.path.join(PDF_FOLDER, pdf_name)
        with open(pdf_path, "wb") as f:
            f.write(pdf_bytes)

        country_display = f"{country} ({state})" if state else country
        print(f"✅  {camp_name} / {year} / {country_display} / {region}")
        log_rows.append([camp_name, year, "✅ ok", country_display, region])

    except Exception as e:
        print(f"❌  {e}")
        errors.append({"file": pdf_name, "url": pdf_url, "error": str(e)})
        log_rows.append([pdf_name, "?", f"❌ {e}", "", ""])

# ── 13. Résumé console ────────────────────────────────────────
print(f"\n{'═'*60}")
print(f"  ✅ {len(results):>3} camps 2026 extraits")
print(f"  ⏭️  {len(skipped):>3} PDFs ignorés (autre année)")
print(f"  ❌ {len(errors):>3} erreurs")
print(f"{'═'*60}")

# ── 14. Tableau de log ────────────────────────────────────────
df_log = pd.DataFrame(log_rows, columns=["Fichier","Année","Statut","Pays","Région"])
display(df_log.style
    .set_properties(**{'font-size':'11px','text-align':'left'})
    .set_table_styles([
        {'selector':'th','props':[('background-color','#1a3a5c'),('color','white')]},
        {'selector':'tr:nth-child(even)','props':[('background-color','#e8f0fe')]}
    ])
)

# ── 15. Tableau récap camps 2026 ──────────────────────────────
if results:
    KEY_DISPLAY = [
        "pdf_file","camp_name","country","state","region",
        "camp_location","date_start","date_end",
        "age_range","camp_fee_eur","email","application_deadline"
    ]
    rows = [{k: d.get(k,"—") for k in KEY_DISPLAY} for d in results]
    print("\n🏕️  CAMPS 2026 EXTRAITS :")
    display(pd.DataFrame(rows).style
        .set_properties(**{'font-size':'11px','text-align':'left',
                           'white-space':'pre-wrap'})
        .set_table_styles([
            {'selector':'th','props':[('background-color','#2e6da4'),('color','white')]},
            {'selector':'tr:nth-child(even)','props':[('background-color','#f0f4ff')]}
        ])
    )

# ── 16. Stats par région ──────────────────────────────────────
if results:
    df_regions = (
        pd.DataFrame(results)[["region","country"]]
        .groupby("region")
        .agg(
            nb_camps = ("country","count"),
            pays     = ("country", lambda x: ", ".join(sorted(set(x))))
        )
        .reset_index()
        .sort_values("nb_camps", ascending=False)
    )
    print("\n🌍 RÉPARTITION PAR RÉGION :")
    display(df_regions.style
        .set_properties(**{'font-size':'11px','text-align':'left'})
        .set_table_styles([
            {'selector':'th','props':[('background-color','#1a5c3a'),('color','white')]},
            {'selector':'tr:nth-child(even)','props':[('background-color','#e8f5ee')]}
        ])
    )

# ── 17. Sauvegarde JSON ───────────────────────────────────────
output = {
    "year"        : TARGET_YEAR,
    "source"      : BASE_URL,
    "total_camps" : len(results),
    "skipped"     : len(skipped),
    "errors"      : errors,
    "camps"       : results
}

with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"\n💾 JSON sauvegardé : {OUTPUT_JSON}")
print(f"📁 PDFs 2026 dans  : {PDF_FOLDER}/")

# ── 18. Téléchargement JSON ───────────────────────────────────
from google.colab import files
files.download(OUTPUT_JSON)
print("✅ Done !")

🌐 Scraping de la page principale...
🔗 131 liens PDF trouvés

[  1/131] ⚙️  Sound-of-music.pdf...✅  Lions Youthcamp "Sound of Music" / 2026 / Austria / Europe
[  2/131] ⚙️  Sound.pdf...✅  Brochure / 2026 / Austria / Europe
[  3/131] ⚙️  Brochure.pdf...✅  Lions Youthcamp "Käsköpfle together" / 2026 / Austria / Europe
[  4/131] ⚙️  Brochure.pdf...✅  Lions Youthcamp "Vienna and around" / 2026 / Austria / Europe
[  5/131] ⚙️  AUSTRIA-Campinfo-2023.pdf...⏭️ AUSTRIA-Campinfo-2023 / Austria / 2023 ignoré
[  6/131] ⚙️  Brussels.pdf...✅  Brussels Lions Youth Camp / 2026 / Belgium / Europe
[  7/131] ⚙️  Belgiium_Facts-in-brief-2025.pdf...⏭️ Belgiium_Facts-in-brief-2025 / Belgium / 2025 ignoré
[  8/131] ⚙️  Cipro.pdf...⏭️ Lions International Youth Camp "Nicos Michael" / Cipro / 2023 ignoré
[  9/131] ⚙️  Croazia-Letak-YEC-A5.pdf...⏭️ International Lions Youth Camp Discover Croatia "Istria" / Croatia / 2025 ignoré
[ 10/131] ⚙️  Danimarca.pdf...✅  Lions Camp Hirtshals / 2026 / Denmark / Europe
[ 11/131] ⚙️  Camp-A.pdf...⏭️ Camp-A / Denmark / 2023 ignoré
[ 12/131] ⚙️  Danimarca.pdf...⏭️ Lions Camp Western Jutland / Denmark / None ignoré
[ 13/131] ⚙️  Active-Living.pdf...✅  Active Living - Green Thinking / 2026 / Denmark / Europe
[ 14/131] ⚙️  Catch-the-future.pdf...✅  Catch the Future between Hearth, Heaven and Sea / 2026 / Denmark / Europe
[ 15/131] ⚙️  Estonia.pdf...✅  29th Estonian Lions Youth Camp "EESTI VÄGI" / 2026 / Estonia / Europe
[ 16/131] ⚙️  Lions_D120_Estonia_YC_2025.pdf...⏭️ Lions_D120_Estonia_YC_2025 / Estonia / 2025 ignoré
[ 17/131] ⚙️  Lakeland%20Vibes%20-%20Lions%20Youth%20Camp%202026.pdf...⏭️ Lions Youth Camp - Lakeland Vibes / 1614198 / None ignoré
[ 18/131] ⚙️  Perigord.pdf...✅  Lions Camp du Perigord Noir / 2026 / France / Europe
[ 19/131] ⚙️  Paris.pdf...⏭️ Paris / France / 2025 ignoré
[ 20/131] ⚙️  Guide-camp-YEC-France-2026-V4-_20251102_134949_0000.pdf...✅  Guide Camp YEC MD 103 / 2026 / France / Europe
[ 21/131] ⚙️  Germania.pdf...✅  Brochure / 2026 / Germany / Europe
[ 22/131] ⚙️  The-hidden-Treasures.pdf...✅  The hidden treasures of Central-Hungary / 2026 / Hungary / Europe
[ 23/131] ⚙️  Discover-2026.pdf...✅  Discover Ireland Youth Camp / 2026 / Ireland / Europe
[ 24/131] ⚙️  Islanda.pdf...✅  Living in harmony with nature Lions Camp / 2026 / Iceland / Europe
[ 25/131] ⚙️  Israele.pdf...✅  Holy Land Camp / 2026 / Israel / Middle East
[ 26/131] ⚙️  Campo-Italia.pdf...❌  name 'none' is not defined
[ 27/131] ⚙️  Trinacria.pdf...❌  name 'none' is not defined
[ 28/131] ⚙️  Campo-Amicizia.pdf...❌  name 'none' is not defined
[ 29/131] ⚙️  YCE_CampoEmilia_ENG_26.pdf...❌  name 'none' is not defined
[ 30/131] ⚙️  Valtellina.pdf...❌  name 'none' is not defined
[ 31/131] ⚙️  Alpe-Adria.pdf...❌  name 'none' is not defined
[ 32/131] ⚙️  Traveling.pdf...❌  name 'none' is not defined
[ 33/131] ⚙️  Vesuvio.pdf...❌  name 'none' is not defined
[ 34/131] ⚙️  Campo-dei-Laghi.pdf...❌  name 'none' is not defined
[ 35/131] ⚙️  Azzurro.pdf...❌  name 'none' is not defined
[ 36/131] ⚙️  flyer-Campo-Toscana.pdf...❌  name 'none' is not defined
[ 37/131] ⚙️  Campo-Apulia.pdf...❌  name 'none' is not defined
[ 38/131] ⚙️  Freewheeling-.pdf...❌  name 'none' is not defined
[ 39/131] ⚙️  PROGRAMMA.pdf...❌  name 'none' is not defined
[ 40/131] ⚙️  Lithuania.pdf...✅  Lions Youth Camp "Life is..." / 2026 / Lithuania / Europe
[ 41/131] ⚙️  Peace.pdf...⏭️ Peace / Norway / 2022 ignoré
[ 42/131] ⚙️  beitostlen-2025.pdf...⏭️ beitostlen-2025 / Norway / 2025 ignoré
[ 43/131] ⚙️  lions-camp-Beitostlen-2026.pdf...✅  Lions Camp Beitostølen, International camp for youth with visual or physical impairment. / 2026 / Norway / Europe
[ 44/131] ⚙️  Lions-Camp-Imagine-Peace-2026.pdf...✅  Lions Campo Imagine Peace / 2026 / Norway / Europe
[ 45/131] ⚙️  Flyer-Lions-Camp-Hardangervidda-2026.pdf...✅  Lions Camp Hardangervidda (Survival Camp) / 2026 / Norway / Europe
[ 46/131] ⚙️  Polonia.pdf...✅  Lions International Watersports Camp / 2026 / Poland / Europe
[ 47/131] ⚙️  POLAND-2025.pdf...⏭️ POLAND-2025 / Poland / 2025 ignoré
[ 48/131] ⚙️  Transylvania.pdf...✅  Discover Transylvania International Lions Camp / 2026 / Romania / Europe
[ 49/131] ⚙️  Serbia.pdf...✅  Lions Camp "Danube" Novi Sad / 2026 / Serbia / Europe
[ 50/131] ⚙️  Two-Countries.pdf...✅  Lions International Youth Camp Two Countries, One Adventure / 2026 / Slovakia / Europe
[ 51/131] ⚙️  Slovacchia.pdf...✅  Brochure / 2026 / Slovakia / Europe
[ 52/131] ⚙️  Slovenia.pdf...✅  Catch the rainbow Lions Youth Exchange Camp / 2026 / Slovenia / Europe
[ 53/131] ⚙️  Mar-Mediterraneo.pdf...✅  Lions Camp Mar Mediterraneo / 2026 / Spain / Europe
[ 54/131] ⚙️  Environment.pdf...✅  Lions Camp Environment and Sustainability / 2026 / Sweden / Europe
[ 55/131] ⚙️  Svezia.pdf...✅  Brochure / 2026 / Sweden / Europe
[ 56/131] ⚙️  Svizzera.pdf...✅  Swiss Nature Experience Lions Camp / 2026 / Switzerland / Europe
[ 57/131] ⚙️  Swiss-Historical.pdf...✅  Swiss Historical Experience / 2026 / Switzerland / Europe
[ 58/131] ⚙️  Building-friendships---www.lions.nl.pdf...✅  Hart Van Brabant / 2026 / Netherlands / Europe
[ 59/131] ⚙️  Building-friendships---www.lions.nl.pdf...✅  Building-friendships---www.lions.nl / 2026 / Netherlands / Europe
[ 60/131] ⚙️  Building-friendships---www.lions.nl.pdf...✅  Lekker Dutch 2026 / 2026 / Netherlands / Europe
[ 61/131] ⚙️  Turchia.pdf...✅  Lions Aegean Bzreeze Camp / 2026 / Turkey / Europe
[ 62/131] ⚙️  Izmir.pdf...⏭️ Izmir / Turkey / 2024 ignoré
[ 63/131] ⚙️  Turchia.pdf...✅  Youth Exchange Bursa Camp / 2026 / Turkey / Europe
[ 64/131] ⚙️  Turchia.pdf...✅  Lions Istanbul Fashion & Culture Camp / 2026 / Turkey / Europe
[ 65/131] ⚙️  Turchia.pdf...✅  Lions Istanbul Dancing at Bosphorus Camp / 2026 / Turkey / Europe
[ 66/131] ⚙️  Turchia.pdf...✅  Lions "Catch the spirit of Istanbul" Camp / 2026 / Turkey / Europe
[ 67/131] ⚙️  Turchia.pdf...✅  Together with Istanbul - Twist Camp / 2026 / Turkey / Europe
[ 68/131] ⚙️  University.pdf...✅  Loughborough Legends / 2026 / United Kingdom / Europe
[ 69/131] ⚙️  London-calling.pdf...⏭️ London-calling / United Kingdom / 2025 ignoré
[ 70/131] ⚙️  Woodcreek.pdf...✅  Woodcreek Lions Mountain Adventure / 2026 / Canada (Alberta) / North America
[ 71/131] ⚙️  Leadership.pdf...✅  Lions Leadership Camp / 2026 / Canada (Alberta) / North America
[ 72/131] ⚙️  Charlie-Shaw.pdf...⏭️ - / Canada / 2023 ignoré
[ 73/131] ⚙️  Charlie-Shaw.pdf...✅  Charlie Shaw Lions Camp / 2026 / Canada (Ontario) / North America
[ 74/131] ⚙️  Charlie-Shaw.pdf...⏭️ Charlie-Shaw / Canada / 2023 ignoré
[ 75/131] ⚙️  Charlie-Shaw.pdf...⏭️ Charlie-Shaw / Canada / 2023 ignoré
[ 76/131] ⚙️  Charlie-Shaw.pdf...⏭️ Charlie-Shaw / Canada / 2023 ignoré
[ 77/131] ⚙️  Bill-Evers.pdf...✅  Lion Bill Evers Friendship Youth Exchange Camp / 2026 / Canada (Ontario) / North America
[ 78/131] ⚙️  Kebec.pdf...✅  Lions Kebec Camp Exchange / 2026 / Canada (Quebec) / North America
[ 79/131] ⚙️  Saskacewan.pdf...✅  Saskachewan Canada Lions Camp 2026 / 2026 / Canada (Saskatchewan) / North America
[ 80/131] ⚙️  Arizona-Tucson.pdf...⏭️ Arizona Lions Youth Exchange / United States / 2024 ignoré
[ 81/131] ⚙️  Traveling-Camp.pdf...✅  California Traveling Camp / 2026 / United States (California) / North America
[ 82/131] ⚙️  Teresita.pdf...⏭️ Teresita / United States / 2024 ignoré
[ 83/131] ⚙️  Colorado.pdf...⏭️ Colorado Lions Camp / United States / 2024 ignoré
[ 84/131] ⚙️  USA-Georgia.pdf...✅  Georgia Lions Youth Exchange Camp / 2026 / United States (Georgia) / North America
[ 85/131] ⚙️  Georgia.pdf...⏭️ Georgia / United States / 2025 ignoré
[ 86/131] ⚙️  Iowa-1.pdf...❌  404 Client Error: Categoria non trovata for url: https://www.scambigiovanili-lions.org/images/doc-campi-esteri/USA/Iowa/2026/Iowa-1.pdf
[ 87/131] ⚙️  Boston.pdf...✅  MD 33 Massachusetts Lions / 2026 / United States (Massachusets) / North America
[ 88/131] ⚙️  Boston.pdf...✅  Boston / 2026 / United States (Massachusets) / North America
[ 89/131] ⚙️  Lions-Bear-Camp---MI.pdf...⏭️ Lions Bear Lake Camp / United States / 2025 ignoré
[ 90/131] ⚙️  Spicer.pdf...✅  Lions Camp Spicer / 2026 / United States (Minnesota) / North America
[ 91/131] ⚙️  Chandler.pdf...⏭️ William C.Chandler Lions Youth Camp / United States / 2025 ignoré
[ 92/131] ⚙️  SOuth-Carolina-Travelling.pdf...⏭️ South Carolina Lions International Youth Exchange Program / United States / 2025 ignoré
[ 93/131] ⚙️  TX-Family-Stay.pdf...    ⚠️  Typo année corrigée : 2926 → 2026
✅  Midland, Texas Family Stay Mini Camp / 2026 / United States (Texas) / North America
[ 94/131] ⚙️  Julien-C-Hyer.pdf...    ⚠️  Typo année corrigée : 2926 → 2026
✅  Julien C. Hyer Lions Youth Camp / 2026 / United States (Texas) / North America
[ 95/131] ⚙️  Camp-Vista.pdf...✅  Wisconsin Lions Youth Exchange Camp Vista "One Week, One Camp, One World" / 2026 / United States (Wisconsin) / North America
[ 96/131] ⚙️  Mexico.pdf...✅  Exploring Mexico City and Morelos / 2026 / Mexico / Middle America
[ 97/131] ⚙️  Martinique.pdf...⏭️ Michalon Genevieve/Marie Christiane jean Pierre / Martinica / 2023 ignoré
[ 98/131] ⚙️  El-Dorado.pdf...⏭️ Campamento El Dorado / Argentina / 2025 ignoré
[ 99/131] ⚙️  Friendship.pdf...✅  Friendship beyond borders Camp / 2026 / Brazil / South America
[100/131] ⚙️  South-.pdf...✅  Lions Camp South Brazil / 2026 / Brazil / South America
[101/131] ⚙️  Colombia.pdf...⏭️ Campamento Cultural Y Ecoturistico Binacional (DMF Colombia Y DME Venezuela) / Colombia / None ignoré
[102/131] ⚙️  Colombia.pdf...⏭️ Campamento Cultural Y Ecoturistico / Colombia / None ignoré
[103/131] ⚙️  Colombia.pdf...⏭️ Binacional (DMF Colombia Y DME Venezuela) / Colombia / None ignoré
[104/131] ⚙️  Namibia.pdf...✅  Lions International Exchange Camp "Service without borders: The Spirit of Ubuntu" / 2026 / Namibia / Africa
[105/131] ⚙️  Hammamet.pdf...⏭️ Hannibal Youth Exchange / Tunisia / 2024 ignoré
[106/131] ⚙️  Vision.pdf...✅  Vision Lions Youth Camp / 2026 / Bangladesh / Other
[107/131] ⚙️  Coxs.pdf...⏭️ Coxs / Bangladesh / 2024 ignoré
[108/131] ⚙️  YCE-2025.pdf...⏭️ Macao Lions Camp / China / 2025 ignoré
[109/131] ⚙️  Heritage.pdf...⏭️ Heritage / China / 2024 ignoré
[110/131] ⚙️  YCE-2025.pdf...⏭️ China Lions Camp (Bejing) / China / 2025 ignoré
[111/131] ⚙️  YCE-2025.pdf...⏭️ Hong Kong Lions Camp / China / 2025 ignoré
[112/131] ⚙️  Tokyo.pdf...✅  Tokyo Disneyland & Culture Camp / 2026 / Japan / Asia-Pacific
[113/131] ⚙️  Giappone.pdf...✅  Experience the heart of Japan / 2026 / Japan / Asia-Pacific
[114/131] ⚙️  Fukushima.pdf...✅  Lions Summer Camp in Tohoku / 2026 / Japan / Asia-Pacific
[115/131] ⚙️  Cultural-Heritage-New.pdf...✅  India Cultural Heritage Lions Camp / 2026 / India / Asia-Pacific
[116/131] ⚙️  Cultural-Heritage-New.pdf...✅  Cultural-Heritage-New / 2026 / India / Asia-Pacific
[117/131] ⚙️  Northern-India.pdf...✅  Youth Camp and explore the norhern India / 2026 / India / Asia-Pacific
[118/131] ⚙️  Culture.pdf...✅  Youth Culture Lions Camp / 2026 / India / Asia-Pacific
[119/131] ⚙️  Discover.pdf...✅  Discover India Camp - YCE 2026 / 2026 / India / Asia-Pacific
[120/131] ⚙️  Escapade-New.pdf...✅  Lions Escapade Northeast Youth Camp & Exchange / 2026 / India / Asia-Pacific
[121/131] ⚙️  Namaste-New.pdf...✅  Namaste India (Central) Youth Camp / 2026 / India / Asia-Pacific
[122/131] ⚙️  Bali.pdf...✅  - / 2026 / Indonesia / Asia-Pacific
[123/131] ⚙️  Sumatera.pdf...✅  Lions North Sumatera Youth Camp / 2026 / Indonesia / Asia-Pacific
[124/131] ⚙️  Mongolia.pdf...✅  Leo Lions Camp / 2026 / Mongolia / Asia-Pacific
[125/131] ⚙️  Brochure.pdf...⏭️ Lions Youth Exchange Camp Nepal / Nepal / None ignoré
[126/131] ⚙️  Ceylon.pdf...✅  Leadership Enhancement, cultural understanding and feel geographical differances of Ceylon / 2026 / Sri Lanka / Asia-Pacific
[127/131] ⚙️  Taipei.pdf...✅  Taipei International Lions Youyh Camp / 2026 / China / Asia-Pacific
[128/131] ⚙️  Taiwan.pdf...✅  300 B2 YCE Lions Camp / 2026 / Taiwan / Asia-Pacific
[129/131] ⚙️  Camp-Elim.pdf...✅  Lions International Youth Exchange Camp Elim / 2026 / Australia / Asia-Pacific
[130/131] ⚙️  Tauranga.pdf...⏭️ New Zealand Lions International Youth Camp / New Zealand / None ignoré
[131/131] ⚙️  Brochure-Scambi-Giovanili-MD.pdf...⏭️ Brochure-Scambi-Giovanili-MD / Download / None ignoré

════════════════════════════════════════════════════════════
  ✅  77 camps 2026 extraits
  ⏭️   39 PDFs ignorés (autre année)
  ❌  15 erreurs
════════════════════════════════════════════════════════════

🏕️  CAMPS 2026 EXTRAITS :

🌍 RÉPARTITION PAR RÉGION :

💾 JSON sauvegardé : lions_camps_2026.json
📁 PDFs 2026 dans  : /content/pdf_camps/

✅ Done !

In [ ]:
skipped

[{'file': 'AUSTRIA-Campinfo-2023.pdf',
  'camp_name': 'AUSTRIA-Campinfo-2023',
  'year': '2023'},
 {'file': 'Belgiium_Facts-in-brief-2025.pdf',
  'camp_name': 'Belgiium_Facts-in-brief-2025',
  'year': '2025'},
 {'file': 'Cipro.pdf',
  'camp_name': 'Lions International Youth Camp "Nicos Michael"',
  'year': '2023'},
 {'file': 'Croazia-Letak-YEC-A5.pdf',
  'camp_name': 'International Lions Youth Camp Discover Croatia "Istria"',
  'year': '2025'},
 {'file': 'Camp-A.pdf', 'camp_name': 'Camp-A', 'year': '2023'},
 {'file': 'Danimarca.pdf',
  'camp_name': 'Lions Camp Western Jutland',
  'year': None},
 {'file': 'Lions_D120_Estonia_YC_2025.pdf',
  'camp_name': 'Lions_D120_Estonia_YC_2025',
  'year': '2025'},
 {'file': 'Lakeland%20Vibes%20-%20Lions%20Youth%20Camp%202026.pdf',
  'camp_name': 'Lions Youth Camp - Lakeland Vibes',
  'year': None},
 {'file': 'Paris.pdf', 'camp_name': 'Paris', 'year': '2025'},
 {'file': 'Peace.pdf', 'camp_name': 'Peace', 'year': '2022'},
 {'file': 'beitostlen-2025.pdf',
  'camp_name': 'beitostlen-2025',
  'year': '2025'},
 {'file': 'POLAND-2025.pdf', 'camp_name': 'POLAND-2025', 'year': '2025'},
 {'file': 'Izmir.pdf', 'camp_name': 'Izmir', 'year': '2024'},
 {'file': 'London-calling.pdf', 'camp_name': 'London-calling', 'year': '2025'},
 {'file': 'Charlie-Shaw.pdf', 'camp_name': '-', 'year': '2023'},
 {'file': 'Charlie-Shaw.pdf', 'camp_name': 'Charlie-Shaw', 'year': '2023'},
 {'file': 'Charlie-Shaw.pdf', 'camp_name': 'Charlie-Shaw', 'year': '2023'},
 {'file': 'Charlie-Shaw.pdf', 'camp_name': 'Charlie-Shaw', 'year': '2023'},
 {'file': 'Arizona-Tucson.pdf',
  'camp_name': 'Arizona Lions Youth Exchange',
  'year': '2024'},
 {'file': 'Teresita.pdf', 'camp_name': 'Teresita', 'year': '2024'},
 {'file': 'Colorado.pdf', 'camp_name': 'Colorado Lions Camp', 'year': '2024'},
 {'file': 'Georgia.pdf', 'camp_name': 'Georgia', 'year': '2025'},
 {'file': 'Lions-Bear-Camp---MI.pdf',
  'camp_name': 'Lions Bear Lake Camp',
  'year': '2025'},
 {'file': 'Chandler.pdf',
  'camp_name': 'William C.Chandler Lions\xa0Youth Camp',
  'year': '2025'},
 {'file': 'SOuth-Carolina-Travelling.pdf',
  'camp_name': 'South Carolina Lions International Youth Exchange Program',
  'year': '2025'},
 {'file': 'Martinique.pdf',
  'camp_name': 'Michalon Genevieve/Marie Christiane jean Pierre',
  'year': '2023'},
 {'file': 'El-Dorado.pdf',
  'camp_name': 'Campamento El Dorado',
  'year': '2025'},
 {'file': 'Colombia.pdf',
  'camp_name': 'Campamento Cultural Y Ecoturistico\xa0Binacional (DMF Colombia Y DME Venezuela)',
  'year': None},
 {'file': 'Colombia.pdf',
  'camp_name': 'Campamento Cultural Y Ecoturistico',
  'year': None},
 {'file': 'Colombia.pdf',
  'camp_name': 'Binacional (DMF Colombia Y DME Venezuela)',
  'year': None},
 {'file': 'Hammamet.pdf',
  'camp_name': 'Hannibal Youth Exchange',
  'year': '2024'},
 {'file': 'Coxs.pdf', 'camp_name': 'Coxs', 'year': '2024'},
 {'file': 'YCE-2025.pdf', 'camp_name': 'Macao Lions Camp', 'year': '2025'},
 {'file': 'Heritage.pdf', 'camp_name': 'Heritage', 'year': '2024'},
 {'file': 'YCE-2025.pdf',
  'camp_name': 'China Lions Camp (Bejing)',
  'year': '2025'},
 {'file': 'YCE-2025.pdf', 'camp_name': 'Hong Kong Lions Camp', 'year': '2025'},
 {'file': 'Brochure.pdf',
  'camp_name': 'Lions Youth Exchange Camp Nepal',
  'year': None},
 {'file': 'Tauranga.pdf',
  'camp_name': 'New Zealand Lions International Youth Camp',
  'year': None},
 {'file': 'Brochure-Scambi-Giovanili-MD.pdf',
  'camp_name': 'Brochure-Scambi-Giovanili-MD',
  'year': None}]

In [ ]:
log_rows

[['Lions Youthcamp "Sound of Music"', '2026', '✅ ok', 'Austria', 'Europe'],
 ['Brochure', '2026', '✅ ok', 'Austria', 'Europe'],
 ['Lions Youthcamp "Käsköpfle together"', '2026', '✅ ok', 'Austria', 'Europe'],
 ['Lions Youthcamp "Vienna and around"', '2026', '✅ ok', 'Austria', 'Europe'],
 ['AUSTRIA-Campinfo-2023', '2023', '⏭️ ignoré', '', ''],
 ['Brussels Lions Youth Camp', '2026', '✅ ok', 'Belgium', 'Europe'],
 ['Belgiium_Facts-in-brief-2025', '2025', '⏭️ ignoré', '', ''],
 ['Lions International Youth Camp "Nicos Michael"',
  '2023',
  '⏭️ ignoré',
  '',
  ''],
 ['International Lions Youth Camp Discover Croatia "Istria"',
  '2025',
  '⏭️ ignoré',
  '',
  ''],
 ['Lions Camp Hirtshals', '2026', '✅ ok', 'Denmark', 'Europe'],
 ['Camp-A', '2023', '⏭️ ignoré', '', ''],
 ['Lions Camp Western Jutland', '?', '⏭️ ignoré', '', ''],
 ['Active Living - Green Thinking', '2026', '✅ ok', 'Denmark', 'Europe'],
 ['Catch the Future between Hearth, Heaven and Sea',
  '2026',
  '✅ ok',
  'Denmark',
  'Europe'],
 ['29th Estonian Lions Youth Camp "EESTI VÄGI"',
  '2026',
  '✅ ok',
  'Estonia',
  'Europe'],
 ['Lions_D120_Estonia_YC_2025', '2025', '⏭️ ignoré', '', ''],
 ['Lions Youth Camp - Lakeland Vibes', '?', '⏭️ ignoré', '', ''],
 ['Lions Camp du Perigord Noir', '2026', '✅ ok', 'France', 'Europe'],
 ['Paris', '2025', '⏭️ ignoré', '', ''],
 ['Guide Camp YEC MD 103', '2026', '✅ ok', 'France', 'Europe'],
 ['Brochure', '2026', '✅ ok', 'Germany', 'Europe'],
 ['The hidden treasures of Central-Hungary',
  '2026',
  '✅ ok',
  'Hungary',
  'Europe'],
 ['Discover Ireland Youth Camp', '2026', '✅ ok', 'Ireland', 'Europe'],
 ['Living in harmony with nature Lions Camp',
  '2026',
  '✅ ok',
  'Iceland',
  'Europe'],
 ['Holy Land Camp', '2026', '✅ ok', 'Israel', 'Middle East'],
 ['Campo-Italia.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Trinacria.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Campo-Amicizia.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['YCE_CampoEmilia_ENG_26.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Valtellina.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Alpe-Adria.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Traveling.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Vesuvio.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Campo-dei-Laghi.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Azzurro.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['flyer-Campo-Toscana.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Campo-Apulia.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Freewheeling-.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['PROGRAMMA.pdf', '?', "❌ name 'none' is not defined", '', ''],
 ['Lions Youth Camp "Life is..."', '2026', '✅ ok', 'Lithuania', 'Europe'],
 ['Peace', '2022', '⏭️ ignoré', '', ''],
 ['beitostlen-2025', '2025', '⏭️ ignoré', '', ''],
 ['Lions Camp Beitostølen,\xa0International camp for youth with visual or physical impairment.',
  '2026',
  '✅ ok',
  'Norway',
  'Europe'],
 ['Lions Campo Imagine Peace', '2026', '✅ ok', 'Norway', 'Europe'],
 ['Lions Camp Hardangervidda\xa0(Survival Camp)',
  '2026',
  '✅ ok',
  'Norway',
  'Europe'],
 ['Lions International Watersports Camp', '2026', '✅ ok', 'Poland', 'Europe'],
 ['POLAND-2025', '2025', '⏭️ ignoré', '', ''],
 ['Discover Transylvania International Lions Camp',
  '2026',
  '✅ ok',
  'Romania',
  'Europe'],
 ['Lions Camp "Danube"\xa0Novi Sad', '2026', '✅ ok', 'Serbia', 'Europe'],
 ['Lions International Youth Camp Two Countries, One Adventure',
  '2026',
  '✅ ok',
  'Slovakia',
  'Europe'],
 ['Brochure', '2026', '✅ ok', 'Slovakia', 'Europe'],
 ['Catch the rainbow Lions Youth Exchange Camp',
  '2026',
  '✅ ok',
  'Slovenia',
  'Europe'],
 ['Lions Camp Mar Mediterraneo', '2026', '✅ ok', 'Spain', 'Europe'],
 ['Lions Camp Environment and Sustainability',
  '2026',
  '✅ ok',
  'Sweden',
  'Europe'],
 ['Brochure', '2026', '✅ ok', 'Sweden', 'Europe'],
 ['Swiss Nature Experience Lions Camp',
  '2026',
  '✅ ok',
  'Switzerland',
  'Europe'],
 ['Swiss Historical Experience', '2026', '✅ ok', 'Switzerland', 'Europe'],
 ['Hart Van Brabant', '2026', '✅ ok', 'Netherlands', 'Europe'],
 ['Building-friendships---www.lions.nl',
  '2026',
  '✅ ok',
  'Netherlands',
  'Europe'],
 ['Lekker Dutch 2026', '2026', '✅ ok', 'Netherlands', 'Europe'],
 ['Lions Aegean Bzreeze Camp', '2026', '✅ ok', 'Turkey', 'Europe'],
 ['Izmir', '2024', '⏭️ ignoré', '', ''],
 ['Youth Exchange Bursa Camp', '2026', '✅ ok', 'Turkey', 'Europe'],
 ['Lions Istanbul Fashion & Culture Camp', '2026', '✅ ok', 'Turkey', 'Europe'],
 ['Lions Istanbul Dancing at Bosphorus Camp',
  '2026',
  '✅ ok',
  'Turkey',
  'Europe'],
 ['Lions "Catch the spirit of Istanbul" Camp',
  '2026',
  '✅ ok',
  'Turkey',
  'Europe'],
 ['Together with Istanbul - Twist Camp', '2026', '✅ ok', 'Turkey', 'Europe'],
 ['Loughborough Legends', '2026', '✅ ok', 'United Kingdom', 'Europe'],
 ['London-calling', '2025', '⏭️ ignoré', '', ''],
 ['Woodcreek Lions Mountain Adventure',
  '2026',
  '✅ ok',
  'Canada (Alberta)',
  'North America'],
 ['Lions Leadership Camp',
  '2026',
  '✅ ok',
  'Canada (Alberta)',
  'North America'],
 ['-', '2023', '⏭️ ignoré', '', ''],
 ['Charlie Shaw Lions Camp',
  '2026',
  '✅ ok',
  'Canada (Ontario)',
  'North America'],
 ['Charlie-Shaw', '2023', '⏭️ ignoré', '', ''],
 ['Charlie-Shaw', '2023', '⏭️ ignoré', '', ''],
 ['Charlie-Shaw', '2023', '⏭️ ignoré', '', ''],
 ['Lion Bill Evers Friendship Youth Exchange Camp',
  '2026',
  '✅ ok',
  'Canada (Ontario)',
  'North America'],
 ['Lions Kebec Camp Exchange',
  '2026',
  '✅ ok',
  'Canada (Quebec)',
  'North America'],
 ['Saskachewan Canada Lions Camp 2026',
  '2026',
  '✅ ok',
  'Canada (Saskatchewan)',
  'North America'],
 ['Arizona Lions Youth Exchange', '2024', '⏭️ ignoré', '', ''],
 ['California Traveling Camp',
  '2026',
  '✅ ok',
  'United States (California)',
  'North America'],
 ['Teresita', '2024', '⏭️ ignoré', '', ''],
 ['Colorado Lions Camp', '2024', '⏭️ ignoré', '', ''],
 ['Georgia Lions Youth Exchange Camp',
  '2026',
  '✅ ok',
  'United States (Georgia)',
  'North America'],
 ['Georgia', '2025', '⏭️ ignoré', '', ''],
 ['Iowa-1.pdf',
  '?',
  '❌ 404 Client Error: Categoria non trovata for url: https://www.scambigiovanili-lions.org/images/doc-campi-esteri/USA/Iowa/2026/Iowa-1.pdf',
  '',
  ''],
 ['MD 33 Massachusetts Lions',
  '2026',
  '✅ ok',
  'United States (Massachusets)',
  'North America'],
 ['Boston', '2026', '✅ ok', 'United States (Massachusets)', 'North America'],
 ['Lions Bear Lake Camp', '2025', '⏭️ ignoré', '', ''],
 ['Lions Camp Spicer',
  '2026',
  '✅ ok',
  'United States (Minnesota)',
  'North America'],
 ['William C.Chandler Lions\xa0Youth Camp', '2025', '⏭️ ignoré', '', ''],
 ['South Carolina Lions International Youth Exchange Program',
  '2025',
  '⏭️ ignoré',
  '',
  ''],
 ['Midland, Texas Family Stay Mini Camp',
  '2026',
  '✅ ok',
  'United States (Texas)',
  'North America'],
 ['Julien C. Hyer Lions Youth Camp',
  '2026',
  '✅ ok',
  'United States (Texas)',
  'North America'],
 ['Wisconsin Lions Youth Exchange Camp Vista "One Week, One Camp, One World"',
  '2026',
  '✅ ok',
  'United States (Wisconsin)',
  'North America'],
 ['Exploring Mexico City and Morelos',
  '2026',
  '✅ ok',
  'Mexico',
  'Middle America'],
 ['Michalon Genevieve/Marie Christiane jean Pierre',
  '2023',
  '⏭️ ignoré',
  '',
  ''],
 ['Campamento El Dorado', '2025', '⏭️ ignoré', '', ''],
 ['Friendship beyond borders Camp', '2026', '✅ ok', 'Brazil', 'South America'],
 ['Lions Camp South Brazil', '2026', '✅ ok', 'Brazil', 'South America'],
 ['Campamento Cultural Y Ecoturistico\xa0Binacional (DMF Colombia Y DME Venezuela)',
  '?',
  '⏭️ ignoré',
  '',
  ''],
 ['Campamento Cultural Y Ecoturistico', '?', '⏭️ ignoré', '', ''],
 ['Binacional (DMF Colombia Y DME Venezuela)', '?', '⏭️ ignoré', '', ''],
 ['Lions International Exchange Camp "Service without borders: The Spirit of Ubuntu"',
  '2026',
  '✅ ok',
  'Namibia',
  'Africa'],
 ['Hannibal Youth Exchange', '2024', '⏭️ ignoré', '', ''],
 ['Vision Lions Youth Camp', '2026', '✅ ok', 'Bangladesh', 'Other'],
 ['Coxs', '2024', '⏭️ ignoré', '', ''],
 ['Macao Lions Camp', '2025', '⏭️ ignoré', '', ''],
 ['Heritage', '2024', '⏭️ ignoré', '', ''],
 ['China Lions Camp (Bejing)', '2025', '⏭️ ignoré', '', ''],
 ['Hong Kong Lions Camp', '2025', '⏭️ ignoré', '', ''],
 ['Tokyo Disneyland & Culture Camp', '2026', '✅ ok', 'Japan', 'Asia-Pacific'],
 ['Experience the heart of Japan', '2026', '✅ ok', 'Japan', 'Asia-Pacific'],
 ['Lions Summer Camp in Tohoku', '2026', '✅ ok', 'Japan', 'Asia-Pacific'],
 ['India Cultural Heritage Lions Camp',
  '2026',
  '✅ ok',
  'India',
  'Asia-Pacific'],
 ['Cultural-Heritage-New', '2026', '✅ ok', 'India', 'Asia-Pacific'],
 ['Youth Camp and explore the norhern India',
  '2026',
  '✅ ok',
  'India',
  'Asia-Pacific'],
 ['Youth Culture Lions Camp', '2026', '✅ ok', 'India', 'Asia-Pacific'],
 ['Discover India Camp - YCE 2026', '2026', '✅ ok', 'India', 'Asia-Pacific'],
 ['Lions Escapade Northeast Youth Camp & Exchange',
  '2026',
  '✅ ok',
  'India',
  'Asia-Pacific'],
 ['Namaste India (Central) Youth Camp',
  '2026',
  '✅ ok',
  'India',
  'Asia-Pacific'],
 ['-', '2026', '✅ ok', 'Indonesia', 'Asia-Pacific'],
 ['Lions North Sumatera Youth Camp',
  '2026',
  '✅ ok',
  'Indonesia',
  'Asia-Pacific'],
 ['Leo Lions Camp', '2026', '✅ ok', 'Mongolia', 'Asia-Pacific'],
 ['Lions Youth Exchange Camp Nepal', '?', '⏭️ ignoré', '', ''],
 ['Leadership Enhancement, cultural understanding and feel geographical differances of Ceylon',
  '2026',
  '✅ ok',
  'Sri Lanka',
  'Asia-Pacific'],
 ['Taipei International Lions Youyh Camp',
  '2026',
  '✅ ok',
  'China',
  'Asia-Pacific'],
 ['300 B2 YCE Lions Camp', '2026', '✅ ok', 'Taiwan', 'Asia-Pacific'],
 ['Lions International Youth Exchange Camp Elim',
  '2026',
  '✅ ok',
  'Australia',
  'Asia-Pacific'],
 ['New Zealand Lions International Youth Camp', '?', '⏭️ ignoré', '', ''],
 ['Brochure-Scambi-Giovanili-MD', '?', '⏭️ ignoré', '', '']]

In [ ]:
results

[{'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Austria/2026/Sound-of-music.pdf',
  'pdf_file': 'Sound-of-music.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Austria',
  'camp_name': 'Lions Youthcamp "Sound of Music"',
  'camp_location': '4040 Linz, Elmbergweg 65, Austria',
  'dates': '18 Jul . 1 Aug 2026',
  'age_range': '16/22',
  'camp_fee': '200 €',
  'activities': 'Singing (choir and solo), making music, jamming, experience of singing on stage by microphone, workshops about understanding of other cultures, religions and other Lions topics, teambuilding, inclusion, sports, outdoor and indoor games, meeting with Austrian folk musicians, "lumberjack games"..and finally our great "Final Concert for Peace"!',
  'family_stay': '11 - 18 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Friedrich Drobesh',
  'email': 'yce.austria@gmail.com',
  'phone': 'Application Dead line 31 Mar 2026',
  'website': 'www.lionscamp.at',
  'date_start': '18 Jul',
  'date_end': '1 Aug 2026',
  'age_min': 16,
  'age_max': 22,
  'camp_fee_eur': 200.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Austria/2026/Sound.pdf',
  'pdf_file': 'Sound.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Austria',
  'camp_name': 'Brochure'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Austria/2026/Brochure.pdf',
  'pdf_file': 'Brochure.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Austria',
  'camp_name': 'Lions Youthcamp "Käsköpfle together"'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Austria/2026/Brochure.pdf',
  'pdf_file': 'Brochure.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Austria',
  'camp_name': 'Lions Youthcamp "Vienna and around"'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Belgio/2026/Brussels.pdf',
  'pdf_file': 'Brussels.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Belgium',
  'camp_name': 'Brussels Lions Youth Camp',
  'camp_location': 'Limburg',
  'dates': '18 Jul - 1 Aug 2026',
  'age_range': '17/21',
  'camp_fee': '180 €',
  'activities': 'Discover every corner of Belgium, the heart of Europe! Including visits to Antwerp, Brussels (including the EU Parliament), the Seaside, Flanders Fields, Festivals…',
  'family_stay': '04 - 18 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Stijn Renier',
  'email': 'stijn.renier@renier.be',
  'phone': '+32475782593',
  'application_deadline': '31 Mar 2026',
  'website': 'https://yce.lions.be/',
  'date_start': '18 Jul',
  'date_end': '1 Aug 2026',
  'age_min': 17,
  'age_max': 21,
  'camp_fee_eur': 180.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Danimarca/2026/Danimarca.pdf',
  'pdf_file': 'Danimarca.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Denmark',
  'camp_name': 'Lions Camp Hirtshals'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Danimarca/2026/Active-Living.pdf',
  'pdf_file': 'Active-Living.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Denmark',
  'camp_name': 'Active Living - Green Thinking',
  'camp_location': 'Videbæk, Denmark',
  'dates': '4 - 18 Jul 2026',
  'age_range': '17/21',
  'camp_fee': '100 Euro',
  'activities': 'Agriculture Alternative energy sources Environmental protection History of the Vikings A lot of fun',
  'family_stay': '27 Jun - 4 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Lasse Borgbjerg',
  'email': 'ycein.md@lions.dk',
  'phone': 'Application Dead line 1 Apr 2026',
  'website': 'https://yce.lions.dk/',
  'date_start': '4',
  'date_end': '18 Jul 2026',
  'age_min': 17,
  'age_max': 21,
  'camp_fee_eur': 100.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Danimarca/2026/Catch-the-future.pdf',
  'pdf_file': 'Catch-the-future.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Denmark',
  'camp_name': 'Catch the Future between Hearth, Heaven and Sea',
  'camp_location': 'Hirtshals, Denmark',
  'dates': '4 - 18 Jul 2026',
  'age_range': '17/21',
  'camp_fee': '100 Euro',
  'activities': 'Studies of the history of an old fishing society Visits to modern fishing industries The fantastic nature surrounding Hirtshals',
  'family_stay': '27 Jun - 4 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Lasse Borgbjerg',
  'email': 'ycein.md@lions.dk',
  'phone': 'Application Dead line 1 Apr 2026',
  'website': 'https://yce.lions.dk/',
  'date_start': '4',
  'date_end': '18 Jul 2026',
  'age_min': 17,
  'age_max': 21,
  'camp_fee_eur': 100.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Estonia/2026/Estonia.pdf',
  'pdf_file': 'Estonia.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Estonia',
  'camp_name': '29th Estonian Lions Youth Camp "EESTI VÄGI"'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Francia/2026/Perigord.pdf',
  'pdf_file': 'Perigord.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'France',
  'camp_name': 'Lions Camp du Perigord Noir'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Francia/2026/Guide-camp-YEC-France-2026-V4-_20251102_134949_0000.pdf',
  'pdf_file': 'Guide-camp-YEC-France-2026-V4-_20251102_134949_0000.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'France',
  'camp_name': 'Guide Camp YEC MD 103',
  'age_range': ': 18 to 22 years old',
  'camp_fee': 's : 350€',
  'activities': 'duringthe Cam Swimming, walking, hiking, shopping, cooking and discoveringfrench gastronomy, participatingin municipal welcomeceremonies, visitingcultural, historical, industrialand naturalsites (fabulousAnnecy Lake, Mont Blanc, Evian water bottlingfactoryfor example) ... simplyenjoyingFrance Contacts : Directeur du camp : Marc CHIRON chironmarc@yahoo.fr Site web:h ttps://camplionsfrancophonealpes.com YOUTH CAMP District 103 CW France EXPLORE LA ROCHELLE AND ITS ISLANDS 6 Lions Clubs lookingforwardto welcomingyou Urban & islanddiscovery: La Rochelle city(to wers, aquarium),Fort Boyard,Réisland(cycling,lighthouse), Oléron island(oysterfarming), Aix island(museums, beaches). Seasideactvities: swimming, relaxingon sandybeaches, introduction to sailing (cid:0) Camp: from2026/06/26 to 2026/07/06 –Host families: from2026/07/06 to 2026/07/16 (cid:0) Fees: 300 € -Registration deadline: 2026/04/30-Camp capacity: 12 (cid:0) Person in charge : Alain DREYFUS -+33 6 45 24 87 18 –alain.dreyfus.lions@orange.f yabaxiP © SET SAIL FOR AN ATLANTIC ADVENTURE Studentsfromaroundthe world, come and experiencethe Atlantic coastin a unique way. SUMMER 2026 : ADVENTURE CALLS YOU ! Camp International LIONS CLUB-PAYS AUDOMAROIS Water sports International meeting INFORMATIONS : Exploration and nature Historic center HOST FAMILY : 2026/06/29-2026/07/05 CAMP : 2026/07/05-2026/07/15 CAMP PRICE : 300€ CITY : SAINT-OMER (North of France) PAULINE BOULET (PRESIDENT) paulineboulet62@hotmail.fr NICOLAS FRANCOIS : lionsclubpaysaudomarois@gmail.com LIONS CAMP YCE EAST WOOD Place of the camp : Niederbronn-les-bains (near Strasbourg) Theme of the camp : Nature and French Heritage Language: English Home familystay: July 16th to July 26th 2026 Date of the camp : July 26th to August 5th 2026',
  'email': ': danielle.lemarie@orange.fr',
  'camp_fee_eur': 350.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Germania/2026/Germania.pdf',
  'pdf_file': 'Germania.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Germany',
  'camp_name': 'Brochure'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Ungheria/2026/The-hidden-Treasures.pdf',
  'pdf_file': 'The-hidden-Treasures.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Hungary',
  'camp_name': 'The hidden treasures of Central-Hungary',
  'camp_location': 'Monor, Budapest',
  'dates': '3 11 Aug 2026',
  'age_range': '18/22',
  'camp_fee': '250 €',
  'activities': 'Activities: horse-drawn carriage ride, walk in the cellar village, wine tasting, folk dancing, wellness, swimming, sensitisation programmes, City tour in Budapest (Buda Castle, Parliament, Heroes square and more…), Budapest by night...".',
  'family_stay': '20 -27 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Andras Fesus',
  'email': 'fa@europr.hu',
  'phone': '+36303303063',
  'application_deadline': '28 Feb 2026',
  'website': 'https://www.lions.hu/youth-camp-in-hungary',
  'age_min': 18,
  'age_max': 22,
  'camp_fee_eur': 250.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Irlanda/2026/Discover-2026.pdf',
  'pdf_file': 'Discover-2026.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Ireland',
  'camp_name': 'Discover Ireland Youth Camp',
  'camp_location': 'Waterford & Dublin, Ireland',
  'dates': '20 Jun - 4 Jul 2026',
  'age_range': '16/21',
  'camp_fee': '200 €',
  'activities': 'Walking. cycling, art, social media, drama, Irish sports, team building, swimming, cooking, educational visits, community activation projects, visits to different areas of the south east of Ireland and Dublin.',
  'family_stay': 'Official Language English',
  'camp_contact': 'Eoin O’Neill',
  'email': 'YouthExchange@lionsclubs.ie',
  'phone': '+353872270803',
  'application_deadline': '21 Feb 2026',
  'website': 'www.lionsclubs.ie',
  'date_start': '20 Jun',
  'date_end': '4 Jul 2026',
  'age_min': 16,
  'age_max': 21,
  'camp_fee_eur': 200.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Islanda/2026/Islanda.pdf',
  'pdf_file': 'Islanda.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Iceland',
  'camp_name': 'Living in harmony with nature Lions Camp',
  'camp_location': 'Hafnar&örður',
  'dates': '1-10 Jul 2026',
  'age_range': '18/21',
  'camp_fee': '200 €',
  'activities': 'Field trips in unique landscape and nature. Reykjavík, the capital, culture and ac>vi>es. Seminar on IT. Great swimming pool/waterworld onsite.',
  'family_stay': 'NO',
  'official_language': 'English',
  'camp_contact': 'Björg Bára HalldórsdóKr',
  'email': 'bjorgbarah@gmail.com',
  'phone': '+354 8635422',
  'application_deadline': '15 Mar 2026',
  'website': '',
  'date_start': '1',
  'date_end': '10 Jul 2026',
  'age_min': 18,
  'age_max': 21,
  'camp_fee_eur': 200.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Israele/2026/Israele.pdf',
  'pdf_file': 'Israele.pdf',
  'year': '2026',
  'region': 'Middle East',
  'country': 'Israel',
  'camp_name': 'Holy Land Camp'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Lituania/2026/Lithuania.pdf',
  'pdf_file': 'Lithuania.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Lithuania',
  'camp_name': 'Lions Youth Camp "Life is..."',
  'camp_location': 'Lithuania',
  'dates': '02 - 12 Aug 2026',
  'age_range': '16/20',
  'camp_fee': '150 €',
  'activities': 'Discovering Lithuania and friendship, discussions on various topics, sharing knowledge and ideas, discovering different cultures.',
  'family_stay': '26 Jul 02 Aug 2026',
  'official_language': 'English',
  'camp_contact': 'Tomas Grigas',
  'email': 'tomas@vilniuslions.lt',
  'phone': '+37068667876',
  'application_deadline': '15 Mar 2026',
  'website': '',
  'date_start': '02',
  'date_end': '12 Aug 2026',
  'age_min': 16,
  'age_max': 20,
  'camp_fee_eur': 150.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Norvegia/2026/lions-camp-Beitostlen-2026.pdf',
  'pdf_file': 'lions-camp-Beitostlen-2026.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Norway',
  'camp_name': 'Lions Camp Beitostølen,\xa0International camp for youth with visual or physical impairment.'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Norvegia/2026/Lions-Camp-Imagine-Peace-2026.pdf',
  'pdf_file': 'Lions-Camp-Imagine-Peace-2026.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Norway',
  'camp_name': 'Lions Campo Imagine Peace',
  'phone': ': +47 906 44 258',
  'activities': 'We visit sightings in Norway/Østfold/',
  'age_range': 'limits: 18-22 years activities.',
  'camp_fee': ': 200 Euro',
  'camp_fee_eur': 200.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Norvegia/2026/Flyer-Lions-Camp-Hardangervidda-2026.pdf',
  'pdf_file': 'Flyer-Lions-Camp-Hardangervidda-2026.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Norway',
  'camp_name': 'Lions Camp Hardangervidda\xa0(Survival Camp)',
  'age_range': 'Limit: 18 – 23 years going to nearby places for extraordinary'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Polonia/2026/Polonia.pdf',
  'pdf_file': 'Polonia.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Poland',
  'camp_name': 'Lions International Watersports Camp'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Romania/2026/Transylvania.pdf',
  'pdf_file': 'Transylvania.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Romania',
  'camp_name': 'Discover Transylvania International Lions Camp',
  'camp_location': 'Cluj, Oradea, Vultureni, Beliș, Transylvania, Romania',
  'dates': '29 Jul - 5 Aug 2026',
  'age_range': '18/24',
  'camp_fee': '250 Euro',
  'activities': 'The Program will include visits to important tourists attraction in Transylvania county, Romania, like: Cluj, Oradea and Jibou cities, Dracula (Bran) castle, lakes and waterfalls in Apuseni Mountains, Nymphaea aquapark, etc. There will many fun and personal development activities prepared by the Leo-Lions including countries presentantions and service activities.',
  'family_stay': '23-29 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Alina Teodora Iosep',
  'email': 'alina.iosep@gmail.com',
  'phone': '+40727220500',
  'application_deadline': '12 Maj 2026',
  'website': '',
  'date_start': '29 Jul',
  'date_end': '5 Aug 2026',
  'age_min': 18,
  'age_max': 24,
  'camp_fee_eur': 250.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Serbia/2026/Serbia.pdf',
  'pdf_file': 'Serbia.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Serbia',
  'camp_name': 'Lions Camp "Danube"\xa0Novi Sad'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Slovakia/2026/Two-Countries.pdf',
  'pdf_file': 'Two-Countries.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Slovakia',
  'camp_name': 'Lions International Youth Camp Two Countries, One Adventure',
  'camp_location': 'Slovakia, Banska Bystrica Slovakia, Opava Czech',
  'dates': '11/25 Jul 2026',
  'age_range': '18/22',
  'camp_fee': '250 €',
  'activities': 'include: hiking, rafting, outdoor adventures, castles, museums, cities. Be ready and willing to HIKE in the mountains! We cannot accept vegans or vegetarians. Family stay: Participants will stay in families in Czech republic or Slovakia.',
  'family_stay': '4/11 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Tomas Renco',
  'email': 'youthexchanged122@gmail.com',
  'phone': '+421 911 989 763',
  'application_deadline': '15 Mar 2026',
  'website': '',
  'age_min': 18,
  'age_max': 22,
  'camp_fee_eur': 250.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Slovakia/2026/Slovacchia.pdf',
  'pdf_file': 'Slovacchia.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Slovakia',
  'camp_name': 'Brochure'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Slovenia/2026/Slovenia.pdf',
  'pdf_file': 'Slovenia.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Slovenia',
  'camp_name': 'Catch the rainbow Lions Youth Exchange Camp',
  'camp_location': 'Slovenia',
  'dates': '17 - 27 Jul 2026',
  'age_range': '18/24',
  'camp_fee': '250 Euro',
  'activities': '"sports activities (hiking, rafting, swimming) cultural activities (getting to know Slovenian history and heritage and cuisine - we will cook traditional food) going around the country and getting to know Slovenian ""pearls""socialising and ""having the time of your life"" ***please send your application to incoming.youth.exchange@lions.si"',
  'family_stay': '3 - 10 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Marko Kužner',
  'email': 'youth.exchange@lions.si',
  'phone': '+38641608350',
  'application_deadline': '31 Mar 2026',
  'website': 'https://www.facebook.com/lionsyouthexchangeslovenia',
  'date_start': '17',
  'date_end': '27 Jul 2026',
  'age_min': 18,
  'age_max': 24,
  'camp_fee_eur': 250.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Spagna/2026/Mar-Mediterraneo.pdf',
  'pdf_file': 'Mar-Mediterraneo.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Spain',
  'camp_name': 'Lions Camp Mar Mediterraneo',
  'camp_location': 'Elche',
  'dates': '29 Jun - 10 Jul 2026',
  'age_range': '18/20',
  'camp_fee': '450 €',
  'activities': 'in nature and with animals. Social activities: Melvin Jones Eyeglasses Recycling Center, guide dogs training activity, parties, team games and environment awareness experience by the beach. Elche: City hall, historic center and world heritage sites. Alicante: Museums, historic center, port. Santa Pola: Museums, beach...',
  'family_stay': '20-29 Jun 2026',
  'official_language': 'English-Spanish',
  'camp_contact': 'Gemma Rodriguez Cortes',
  'email': 'yce.md116spain.lci@gmail.com',
  'phone': '+34649915077',
  'application_deadline': '15 Mar 2026',
  'website': 'WWW.LIONSCAMPMARMEDITERRANEO.COM',
  'date_start': '29 Jun',
  'date_end': '10 Jul 2026',
  'age_min': 18,
  'age_max': 20,
  'camp_fee_eur': 450.0},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Svezia/2026/Environment.pdf',
  'pdf_file': 'Environment.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Sweden',
  'camp_name': 'Lions Camp Environment and Sustainability',
  'camp_location': 'Northern parts of Sweden-Sollefteå with surroundings',
  'dates': '25 Jul - 8 Aug 2026',
  'age_range': '17/22',
  'camp_fee': 'No',
  'activities': 'Sustainable development and environmental protection, nature adventures, culture experiences, local history, forest, water and wind power.',
  'family_stay': '18/25 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Annika Velin',
  'email': 'youth-in@lions.se',
  'phone': '0702974495',
  'application_deadline': '15 Dec 2025',
  'website': '',
  'date_start': '25 Jul',
  'date_end': '8 Aug 2026',
  'age_min': 17,
  'age_max': 22,
  'camp_fee_eur': None},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Svezia/2026/Svezia.pdf',
  'pdf_file': 'Svezia.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Sweden',
  'camp_name': 'Brochure'},
 {'source_url': 'https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Svizzera/2026/Svizzera.pdf',
  'pdf_file': 'Svizzera.pdf',
  'year': '2026',
  'region': 'Europe',
  'country': 'Switzerland',
  'camp_name': 'Swiss Nature Experience Lions Camp',
  'camp_location': 'Switzerland, Alte Gärtnerei,',
  'dates': '25 Jul - 8 Aug 2026',
  'age_range': '16/22',
  'camp_fee': '0',
  'activities': 'Nature in the Central part of Switzerland - Swiss aviation - Visiting the Swiss parliament - Seeing the transport museum - Visiting typical Swiss cities - Hiking in the mountains - Sports activities, in particular Swiss sports - Celebration of the Swiss National Day with families and friends - and much more ...',
  'family_stay': '11 - 25 Jul 2026',
  'official_language': 'English',
  'camp_contact': 'Petra Wildemann',
  'email': 'YouthExchangeSwitzerland@lionsmd102.ch',
  'phone': '+41 76 322 57 16',

In [ ]:
pdf_url="https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Danimarca/2026/Danimarca.pdf"

#https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Giappone/2026/Giappone.pdf"
#pdf_url="https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Turchia/2026/Turchia.pdf"
#pdf_url="https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Austria/2026/Brochure.pdf"
#pdf_url="https://www.scambigiovanili-lions.org/images/doc-campi-esteri/Svizzera/2026/Svizzera.pdf"
guess_country_region(pdf_url)

('Denmark', 'Europe', None, '2026')